strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - build
  - env

pep8:
  options:
    max-line-length: 100

pylint:
  disable:
    - super-init-not-called
    - unsubscriptable-object

mccabe:
  run: true
